export const equipmentList = [
  { id: 1, name: 'Lawn Mower' },
  { id: 2, name: 'Hedge Trimmer' },
  { id: 3, name: 'Leaf Blower' },
  { id: 4, name: 'String Trimmer (Weed Eater)' },
  { id: 5, name: 'Chainsaw' },
  { id: 6, name: 'Garden Shears' },
  { id: 7, name: 'Pruning Saw' },
  { id: 8, name: 'Rakes (Leaf, Garden, Lawn)' },
  { id: 9, name: 'Shovels (Round, Square, Digging)' },
  { id: 10, name: 'Wheelbarrow' },
  { id: 11, name: 'Garden Hoe' },
  { id: 12, name: 'Trowel' },
  { id: 13, name: 'Mattock' },
  { id: 14, name: 'Loppers' },
  { id: 15, name: 'Cultivator' },
  { id: 16, name: 'Sprinklers' },
  { id: 17, name: 'Garden Fork' },
  { id: 18, name: 'Mulching Lawn Mower' },
  { id: 19, name: 'Garden Cart' },
  { id: 20, name: 'Edger' },
  { id: 21, name: 'Tiller' },
  { id: 22, name: 'Watering Can' },
  { id: 23, name: 'Leaf Vacuum' },
  { id: 24, name: 'Pressure Washer' },
  { id: 25, name: 'Garden Gloves' },
  { id: 26, name: 'Kneeling Pad' },
  { id: 27, name: 'Garden Sprayer' },
  { id: 28, name: 'Soil pH Tester' },
  { id: 29, name: 'Wheel Edger' },
  { id: 30, name: 'Manual Lawn Aerator' }
];
